config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flights, only: [:new, :create, :index, :show]
  resources :bookings
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: :from_airport_id, class_name: "Flight"
    has_many :arriving_flights, foreign_key: :to_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :from_airport, class_name: "Airport"
    belongs_to :to_airport, class_name: "Airport"
    has_many :bookings
    has_many :passengers, through: :bookings
   
    
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
      @booking = Booking.new
      @flight = Flight.find(params[:flight_id])
      @count = params[:seat].to_i
      @count.times { @booking.passengers.build }
    end
  
    def create
      @booking = Booking.new(booking_params)
     

      if @booking.save
        @booking.passengers.each do |pass|
          PassengerMailer.confirmation_email(pass, @booking).deliver_now!
        end
  
        flash[:success] = "Booking successful!"
        redirect_to booking_path(@booking)
      else
        flash[:danger] = "Flight booking error! #{@booking.errors.messages}"
        render :new
      end
    end
  
  
    def show
      @booking = Booking.find(params[:id])
      @flight = Flight.find(@booking.flight_id)
    end
  
    def booking_params
      params.require(:booking).permit(:flight_id,passengers_attributes: [:name,:email])
    end
  end

app/controllers/flights_controller.rb
require "date"
class FlightsController < ApplicationController
	def index
	  @flights = Flight.all
	  unless params[:flight_dates].nil?
	
		@available_flights = Flight.where(from_airport_id: params[:from_airport_id],to_airport_id: params[:to_airport_id],start: params[:flight_dates].to_date.all_day)
	
		@seat = params[:passenger_seats].to_i
	  end
	end
  
	def show
	  @flight = Flight.find(params[:id])
	end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= form_for @booking do |f| %>
  <% i = 1 %>
  <%= f.fields_for :passengers do |passenger| %>
    <%= "Passenger #{i}" %><br />
    <%= passenger.label :name, "Name" %>
    <%= passenger.text_field :name %><br />
    <%= passenger.label :email,"Email" %>
    <%= passenger.email_field :email %><br />
    <% i+=1 %>
  <% end %>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  <%= f.submit "Confirm Tickets" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking information</h1>
<h3>Booking for flight: <%= link_to @flight.from_airport_id, flight_path(@flight) %> </h3>
<h3>Passenger details: </h3>
<% @booking.passengers.each do |p| %>
  <h5><%= p.name %></h5>
<% end %>
<%= link_to "Back to root path",root_path %>

app/views/flights/index.html.erb
<h1>Flights</h1>
<%= form_with url: "/flights", method: :get do %>
<% @airports = Airport.all.map{|ap| [ap.code,ap.id]}.uniq{|ap| ap[0]} %>
<% @flight_dates = Flight.all.map{|flight| [flight.start.to_date,flight.start]}.uniq{|flight| flight[0]} %>
<% @seats = [[1,1],[2,2],[3,3],[4,4]] %>
 <%= select_tag(:from_airport_id,options_for_select(@airports),{prompt: "From?"}) %><br />
 <%= select_tag(:to_airport_id,options_for_select(@airports),{prompt: "To?"}) %><br />
<%= select_tag(:flight_dates,options_for_select(@flight_dates),{prompt: "Date?"}) %><br />
<%= select_tag(:passenger_seats,options_for_select(@seats),{prompt: "No of passengers?"}) %><br />
<%= submit_tag "Search" %>
<% end %>
<% unless @available_flights.nil? %>
<%  @available_flights.each do |flight| %>
  <%= flight.from_airport.code %>
  <%= flight.to_airport.code %>
<% end %>
<%end%>
<h3>Fill the booking details </h3>
<% unless @available_flights.nil? %>
  <%= form_with url: "/bookings/new", method: :get do |form| %>
    <% @available_flights.each do |flight| %>
    booking_destination:   <%= form.label :booking_destination,flight.to_airport.code %><br> 
    booking_departure:     <%= form.label :booking_departure, flight.from_airport.code %><br>


      <span>Want to book ticket click radio button:<span> <%= form.radio_button :flight_id, flight.id %><br>
    <% end %>
    <%= form.hidden_field :seat, value: @seat %>
    <%= form.submit "Book" %>
  <%end %>
<% end %>





   

app/views/flights/show.html.erb
<h1>Flight Data</h1>
<h3>Flight departure airport code : <%= @flight.from_airport.code %></h3>
<h3>Flight destination airport code : <%= @flight.to_airport.code %></h3>
<h3>Flight departure id: <%= @flight.from_airport_id %></h3>
<h3>Flight destination id: <%= @flight.to_airport_id %></h3>
<h3>Flight duration: <%= @flight.duration %> Hours </h3>
<h3>Flight is scheduled on: <%= @flight.start.to_date %></h3>
<%= link_to "Back to root path", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>